openapi: 3.0.0
info:
  title: My API
  version: 1.0.0
servers:
  - url: http://localhost:3000
paths:
  /:
    get:
      summary: Ping
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string

  /v1/models:
    get:
      summary: Fetch available models
      description: |
        Proxies to the upstream LLM gateway to list models.
      parameters:
        - in: header
          name: x-llm-base-url
          required: true
          schema:
            type: string
          description: Base URL of the LLM service
        - in: header
          name: x-llm-api-key
          required: true
          schema:
            type: string
          description: Your LLM API key
      responses:
        '200':
          description: A list of available models
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: string
        '400':
          description: Missing headers
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  /v1/completions:
    post:
      summary: Create a chat completion
      description: Proxy to upstream LLM for chat completions.
      parameters:
        - in: header
          name: x-llm-base-url
          required: true
          schema:
            type: string
          description: Base URL of the LLM service
        - in: header
          name: x-llm-api-key
          required: true
          schema:
            type: string
          description: Your LLM API key
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CompletionRequest'
      responses:
        '200':
          description: The completion result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CompletionResponse'
        '400':
          description: Missing headers or bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /v1/images/generations:
    post:
      summary: Generate images
      description: Proxy to upstream LLM for image generation.
      parameters:
        - in: header
          name: x-llm-base-url
          required: true
          schema:
            type: string
          description: Base URL of the LLM service
        - in: header
          name: x-llm-api-key
          required: true
          schema:
            type: string
          description: Your LLM API key
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GenerateImageRequest'
      responses:
        '200':
          description: The image generation result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ImageResponse'
        '400':
          description: Missing headers or bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'


components:
  schemas:
    Message:
      type: object
      required:
        - role
        - content
      properties:
        role:
          type: string
          enum: [system, user, assistant]
        content:
          type: string

    CompletionRequest:
      type: object
      required:
        - model
        - messages
      properties:
        model:
          type: string
        messages:
          type: array
          items:
            $ref: '#/components/schemas/Message'
        stream:
          type: boolean
          description: Stream responses as SSE

    Choice:
      type: object
      properties:
        index:
          type: integer
        message:
          $ref: '#/components/schemas/Message'
        finish_reason:
          type: string

    CompletionResponse:
      type: object
      properties:
        id:
          type: string
        object:
          type: string
        created:
          type: integer
        choices:
          type: array
          items:
            $ref: '#/components/schemas/Choice'

    ErrorResponse:
      type: object
      properties:
        error:
          type: string

    GenerateImageRequest:
      type: object
      required:
        - prompt
      properties:
        prompt:
          type: string
          description: Text prompt to generate the image
        model:
          type: string
          description: Model to use for image generation
        n:
          type: integer
          description: Number of images to generate
        size:
          type: string
          description: Dimensions of the generated image (e.g. "1024x1024")
    ImageResponse:
      type: object
      properties:
        created:
          type: integer
          description: Timestamp of image creation
        data:
          type: array
          items:
            type: object
            properties:
              url:
                type: string
                description: URL of the generated image